apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  API_KEY: {{ .Values.shopify.api_key }}
  API_PASSWORD: {{ .Values.shopify.api_password }}
  SHOP_NAME: {{ .Values.shopify.shop_name }}
  WEBHOOK_SECRET: {{ .Values.shopify.webhook_secret }}
